dist: trusty
sudo: false
matrix:
  include:
    - language: go
      go:
        - 1.12.x
      env:
        - GOMAXPROCS=9
      os:
        - linux
      install:
        - go get github.com/axw/gocov/gocov
        - go install github.com/axw/gocov/gocov
        - go get -v -t ./...
      before_install:
        #- openssl aes-256-cbc -k "$super_secret_password" -in fixtures/data.enc -out fixtures/data -d
        #- for i in $(ls fixtures/fixtures_*.enc); do openssl aes-256-cbc -k "$super_secret_password" -in ${i} -out ${i%%.*} -d; done
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
      script:
        - go test -race -v -coverprofile=c.out ./... && echo -e "\n\n\n ✅ SUCCESS \n\n"
        - gocov test ./... > cc.out
      after_success:
        - cp c.out coverage.txt



